### ISSUE TITLE
vehicle shop will not show vehicle category list

### ISSUE THREAD

**Issue by Donnyjohn1** [qbcore-fivem/qb-vehicleshop#2]
before the re-write the shops would show vehicle categoy instead of vehicle class, hoping to have that issue fixed where it reads from the category instead of the class as when it is set to vehicle class alot of cars dont show, even when properly entered in vehicle.lua,

**Comment by Bongmasta406** [comment]
could you provide a copy of your qbcore shared vehicles please

**Comment by xantofrfr** [comment]
If you have a older version of this script, then replace the client.lua with the old one, and make sure u make a categories section in the config :) hope that helps, if u need anything, message me on discord @xanto#7552

**Comment by r0adra93** [comment]
I added the code back in, it's in PR 7

**Comment by LtRevo12** [comment]
I moved my luxury car dealer to another spot. I place all vehicles on the platforms I wanted it to be on. I replaced all coords with the new ones. I also vreated  anew polyzone and chanegd those values. When I walk up to the car the menu pops up, but the issue is that it opens a menu for another car on the floor. Not the one I am at. So when buying the vehicle it buys the other car and not the one you are at. Anyone else who had this issue perhaps?
