### ISSUE TITLE
vehicles disapear from the shop randomly

### ISSUE THREAD

**Issue by Sniper16mvb** [qbcore-fivem/qb-vehicleshop#47]
The vehicles disapear and you can't even interact with the Vehzones but when time pass without touching anything they apear again and dissapear without touching anything. While this happens in the terminal there isn't any error code os something like that.

This happens with all three shops at the same time.

If there is something else that I haven't provided please tell me and I will try to provide it.

**Comment by MrTeaRexx** [comment]
I had this issue and was due to not having a map proxy within the custom mlo / interior. iv attached a map proxies resource which you have to get the name of the interior/mlo ymap name and put it in their 
[map-proxies.zip](https://github.com/qbcore-framework/qb-vehicleshop/files/12324996/map-proxies.zip)
